import { Toaster } from "@/components/ui/sonner";
import { FontProvider } from "@/context/font-provider";
import {
  Collapsible,
  LayoutProvider,
  Variant,
} from "@/context/layout-provider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import NextTopLoader from "nextjs-toploader";
import { CurrentUserServerProvider } from "@/context/current-user-server";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieData = await cookies();
  const defaultOpen = cookieData.get("sidebar_state")?.value !== "false";
  const collapsible: Collapsible = cookieData.get("layout_collapsible")
    ?.value as Collapsible;
  const variant: Variant = cookieData.get("layout_variant")?.value as Variant;

  return (
    <html lang="en" suppressHydrationWarning>
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader color="#BECBD6" showSpinner={false} />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutProvider
            defaultCollapsible={collapsible}
            defaultVariant={variant}
            state={defaultOpen}
          >
            <FontProvider>
              <CurrentUserServerProvider>{children}</CurrentUserServerProvider></FontProvider>
            <Toaster position="top-right" richColors />
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
